version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: on-failure